deployment:
  tasks:
    - export DEPLOYPATH=/home/wlcjwpi80y8j/public_html
    - /bin/rsync -av --delete --exclude ".git/" --exclude ".github/" --exclude "data/" ./ $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/api -type f -name "*.php" -exec chmod 644 {} \;
